// Replace this file with the normalized response from the future TCS scraper/API.
// Keep the object shape stable so the UI does not need to know where events came from.
window.TCS_MOCK_EVENTS = [
  {
    courseId: "TCS-IT-26091",
    title: "Generative AI for Classroom Practice",
    summary: "Build a practical starting point for using generative AI with care, clarity and curriculum intent.",
    category: "IT/AI",
    eventStart: "2026-10-07",
    eventEnd: "2026-10-07",
    closingDate: "2026-09-22",
    level: "Primary · Secondary",
    participantGroup: "Teachers and panel heads",
    format: "Hybrid · Kowloon Tong",
    lastUpdated: "2026-09-18",
    badge: "NEW",
    applyUrl: "https://tcs.edb.gov.hk/"
  },
  {
    courseId: "TCS-STEAM-26044",
    title: "STEAM Design Sprint: From Idea to Prototype",
    summary: "A hands-on design sprint for turning authentic school challenges into testable prototypes.",
    category: "STEAM",
    eventStart: "2026-10-10",
    eventEnd: "2026-10-10",
    closingDate: "2026-09-25",
    level: "Primary · Secondary",
    participantGroup: "STEAM coordinators",
    format: "In person · Tai Po",
    lastUpdated: "2026-09-15",
    badge: "UPDATED",
    applyUrl: "https://tcs.edb.gov.hk/"
  },
  {
    courseId: "TCS-CSD-26028",
    title: "Leading Change Through Collaborative Inquiry",
    summary: "Make professional learning visible through a simple cycle of inquiry, evidence and shared reflection.",
    category: "CSD",
    eventStart: "2026-10-14",
    eventEnd: "2026-10-15",
    closingDate: "2026-09-29",
    level: "School leadership",
    participantGroup: "Middle leaders and aspiring leaders",
    format: "In person · Central",
    lastUpdated: "2026-09-12",
    badge: "NEW",
    applyUrl: "https://tcs.edb.gov.hk/"
  },
  {
    courseId: "TCS-SEC-26102",
    title: "Supporting Learners in the Secondary Classroom",
    summary: "Explore practical routines that create more confident, connected and independent learners.",
    category: "Secondary",
    eventStart: "2026-10-19",
    eventEnd: "2026-10-20",
    closingDate: "2026-10-02",
    level: "Secondary",
    participantGroup: "Secondary subject teachers",
    format: "In person · Sha Tin",
    lastUpdated: "2026-09-08",
    badge: "",
    applyUrl: "https://tcs.edb.gov.hk/"
  },
  {
    courseId: "TCS-IT-26076",
    title: "Digital Citizenship and AI Literacy",
    summary: "Help students make thoughtful decisions about identity, information and AI-assisted work.",
    category: "IT/AI",
    eventStart: "2026-10-21",
    eventEnd: "2026-10-21",
    closingDate: "2026-10-05",
    level: "Primary · Secondary",
    participantGroup: "IT coordinators and teachers",
    format: "Online",
    lastUpdated: "2026-09-11",
    badge: "UPDATED",
    applyUrl: "https://tcs.edb.gov.hk/"
  },
  {
    courseId: "TCS-STEAM-26051",
    title: "Making Mathematics More Visible with Data",
    summary: "Use small data investigations to turn mathematical thinking into something students can see and discuss.",
    category: "STEAM",
    eventStart: "2026-10-24",
    eventEnd: "2026-10-24",
    closingDate: "2026-10-09",
    level: "Primary",
    participantGroup: "Primary mathematics teachers",
    format: "In person · Wan Chai",
    lastUpdated: "2026-09-05",
    badge: "",
    applyUrl: "https://tcs.edb.gov.hk/"
  },
  {
    courseId: "TCS-CSD-26033",
    title: "Wellbeing as a Whole-School Practice",
    summary: "Connect classroom climate, staff culture and student voice in a practical whole-school approach.",
    category: "CSD",
    eventStart: "2026-11-03",
    eventEnd: "2026-11-03",
    closingDate: "2026-10-16",
    level: "School leadership",
    participantGroup: "School leaders and counsellors",
    format: "In person · North Point",
    lastUpdated: "2026-08-28",
    badge: "",
    applyUrl: "https://tcs.edb.gov.hk/"
  },
  {
    courseId: "TCS-SEC-26068",
    title: "Assessment for Learning in English",
    summary: "Design feedback moments that move learning forward without adding unnecessary marking load.",
    category: "Secondary",
    eventStart: "2026-11-06",
    eventEnd: "2026-11-06",
    closingDate: "2026-10-20",
    level: "Secondary",
    participantGroup: "English panel heads",
    format: "Online",
    lastUpdated: "2026-08-30",
    badge: "",
    applyUrl: "https://tcs.edb.gov.hk/"
  },
  {
    courseId: "TCS-IT-26083",
    title: "Getting Started with Physical Computing",
    summary: "A gentle introduction to sensors, simple circuits and computational thinking through making.",
    category: "IT/AI",
    eventStart: "2026-11-11",
    eventEnd: "2026-11-11",
    closingDate: "2026-10-23",
    level: "Primary · Secondary",
    participantGroup: "Technology and STEM teachers",
    format: "In person · Kowloon",
    lastUpdated: "2026-09-02",
    badge: "NEW",
    applyUrl: "https://tcs.edb.gov.hk/"
  },
  {
    courseId: "TCS-STEAM-26062",
    title: "Climate Futures: A Project-Based Learning Lab",
    summary: "Plan a locally grounded project that brings science, design and civic imagination together.",
    category: "STEAM",
    eventStart: "2026-11-17",
    eventEnd: "2026-11-18",
    closingDate: "2026-10-30",
    level: "Secondary",
    participantGroup: "Cross-curricular teams",
    format: "In person · Tuen Mun",
    lastUpdated: "2026-09-01",
    badge: "",
    applyUrl: "https://tcs.edb.gov.hk/"
  },
  {
    courseId: "TCS-CSD-26047",
    title: "From School Data to Better Decisions",
    summary: "Use a light-touch evidence habit to identify priorities and decide what to try next.",
    category: "CSD",
    eventStart: "2026-11-20",
    eventEnd: "2026-11-20",
    closingDate: "2026-11-04",
    level: "School leadership",
    participantGroup: "Senior leaders and coordinators",
    format: "Hybrid · Kowloon Tong",
    lastUpdated: "2026-08-21",
    badge: "",
    applyUrl: "https://tcs.edb.gov.hk/"
  },
  {
    courseId: "TCS-SEC-26091",
    title: "Reading Across the Curriculum",
    summary: "Make disciplinary reading a shared responsibility across the secondary curriculum.",
    category: "Secondary",
    eventStart: "2026-11-25",
    eventEnd: "2026-11-25",
    closingDate: "2026-11-09",
    level: "Secondary",
    participantGroup: "Subject teachers and panel heads",
    format: "Online",
    lastUpdated: "2026-08-25",
    badge: "",
    applyUrl: "https://tcs.edb.gov.hk/"
  }
];
